default:
  image: node:lts-alpine

variables:
  NEXT_TELEMETRY_DISABLED: 1

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules/

stages:
  - install
  - lint
  - test
  - build

install:
  stage: install
  script:
    - yarn install

lint:
  stage: lint
  script:
    - yarn install
    - yarn run lint

test:
  stage: test
  script:
    - yarn install
    - yarn run test

build:
  stage: build
  script:
    - yarn install
    - yarn run build
