name: Prod Workflow

on: 
  push:
    branches: [main]

jobs:
  lint:
    uses: ./.github/workflows/_lint.yml

  unit-tests:
    uses: ./.github/workflows/_unit-tests.yml

  build:
    uses: ./.github/workflows/_build.yml
    needs: [lint, unit-tests]
    with:
      release-version: ${{ github.sha }}
